name: batteries_benchmark_lean_ext
num_files: 1
language: LEAN4
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
is_extraction_request: true
datasets:
  - project: src/data/test/batteries
    files: []
    exclude_files:
      - src/data/test/batteries/.lake
      - src/data/test/batteries/.vscode
      - src/data/test/batteries/BatteriesTest
      - src/data/test/batteries/scripts
      - src/data/test/batteries/docs
      - src/data/test/batteries/Shake
      - src/data/test/batteries/Batteries.lean
      - src/data/test/batteries/bors.toml
      - src/data/test/batteries/lake-manifest.toml
      - src/data/test/batteries/.github
      - src/data/test/batteries/.docker
      - src/data/test/batteries/lakefile.toml
      - src/data/test/batteries/.gitpod.yml
      - src/data/test/batteries/.github
      - src/data/test/batteries/lake-manifest.json